### ISSUE TITLE
Fix typo in readme

### ISSUE THREAD

**Issue by EmmaDawsonDev** [s-leroux/mongoz#2]
the first lines read:

The goal of this project is to add a thin Zig wrapper arround the Mongo C driver to make it easier to use from Zig programs. It is also an educatonal project while I learn the Zig languages -- don't hesitate to submit pull requests if you think I **didn't done the things** the Idiomatic Zig way!

Change the bold text in the final line so it reads: -- don't hesitate to submit pull requests if you think I didn't do things the Idiomatic Zig way!

**Comment by Njong392** [comment]
Can I take on this PR? I'll go ahead and submit one :)

**Comment by jaynarayan-vaishnav** [comment]
If no one's working on this then i would like to contribute

**Comment by Njong392** [comment]
Oops @jaynarayan-vaishnav I already fixed it.

**Comment by jaynarayan-vaishnav** [comment]
It's okay @Njong392 ☺️ i was late will try to find another issue if there is any👍🏻
